name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build script
        run: chmod +x build.sh && ./build.sh
        
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: custom-ubuntu-iso
          path: '../CUSTOM-xenial-20240820-amd64.iso'
          if-no-files-found: warn
